audit_header: false
title: "Dublin's Best Real Estate Training"
description: Kenneth Kelly, a top Real Estate Agent in Dublin, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  # - title: Join Our Team
  #   url: /join-our-team/
  # - title: Events
  #   url: #
  - title: Free Strategy Call
    url: /contact/
client:
  name: KW Ireland
  title:
  license_number:
  about_markdown: |
    While Keller Williams has been operating in the US since 1983, and is the world’s largest estate agency with more than 190,000 agents across 1000 market centres in 38+ countries, we are new to the Irish Market

    Keller Williams. is the world’s largest real estate franchise by agent count and largest in the U.S. by units sold and sales volume, with over 1,000 offices and 180,000 associates across the the Americas, Europe, Africa and Asia.

    The company has grown exponentially since the opening of the first Keller Williams Realty office in 1983, and continues to cultivate an agent-centric, education-based, technology-driven culture that rewards associates as stakeholders.
  market: Dublin
  brand: KW Ireland - Keller Williams
  brokerage:
  address:
  phone: '353876118002'
  phone_type:
  phone2:
  phone2_type:
  email: info@KWIreland.com
  url: http://kennethkcoaching.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how KW Ireland - Keller Williams can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Dublin Real Estate Podcast with Kenneth Kelly'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Dublin Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from KW Ireland - Keller Williams - your professional Dublin Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Dublin, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kenneth Kelly'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Dublin Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
